= Demo-Dokumentation
Vorname Nachname <vorname.nachname@htw-dresden.de>
include::attributes.inc.adoc[]

Praktikumsbeispiel für die Verwendung von Diagrammen mit PlantUML in Asciidoctor.


== PlantUML-Diagramme

Diagramme mit der PlantUML-Notation können im Asciidoctor-Dokument direkt als Block *eingebettet* oder als externe Datei *inkludiert* werden.

=== Funktionstest

Ein Testdiagramm, ob die Vorschau in VS Code bzw. die Generierung mit Asciidoctor funktioniert.

.Testdiagramm
[plantuml, "{diagramsdir}/hello_world", svg]
....
actor Human
(\nWorld\n) #dff
note right of Human : Hello
....

.Graphviz Dot Test
[plantuml, "{diagramsdir}/testdot", svg]
....
@startuml
testdot
@enduml
....

Hinweise zur Einrichtung siehe zugehörige Aufgabenstellung.

=== Eingebettet

Ein Beispiel für ein direkt im Dokument eingebettetes PlantUML-Diagramm.

// diagram placeholder

.Klassendiagramm mit PlantUML 
[plantuml, "{diagramsdir}/syntax-example1", svg]  
....
@startuml
class Graphic 
interface Shape <<Interface>> {
  draw()
}
class "Circle" as c1
class Triangle
class Square

Graphic -> Shape
Shape <|.. c1
Shape <|.. Triangle
Shape <|.. Square
@enduml
....

=== Inkludiert

Ein Beispiel für ein im Dokument inkludiertes PlantUML-Diagramm als externe Datei.
// diagram placeholder

.Klassendiagramm mit PlantUML 
[plantuml, "{diagramsdir}/syntax-example2", svg]  
....
include::{plantumlsdir}/Classdiagram.puml[]
....
